version: 0.0
os: linux
files:
  - source: .
    destination: /home/ec2-user/ticket-club-api/
    overwrite: true
file_exists_behavior: OVERWRITE
hooks:
  AfterInstall:
    - location: aws/setup.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: aws/run.sh
      timeout: 300
      runas: root
